### ISSUE TITLE
Make windArd pip installable

### ISSUE THREAD

**Issue by cfrontin** [cfrontin/windArd#12]
Set up pyproject.toml, etc. to current gold standard.

**Comment by cfrontin** [comment]
I have a working setup at this point, using a `pyproject.toml`. It's a but funky though and probably could be improved. Other than that, the dependencies list is coming together slowly but surely.

**Comment by rafmudaf** [comment]
Do we need both `requirements.txt` and the dependency list in `pyproject.toml`? I think keeping the dependencies in `pyproject.toml` will serve all purposes and the other is redundant. In fact, they're already out of sync since `requirements.txt` doesn't include shapely.

**Comment by rafmudaf** [comment]
If we remove `requirements.txt`, we'll also have to update https://github.com/cfrontin/windArd/blob/develop/.github/workflows/python-tests.yml#L29

**Comment by rafmudaf** [comment]
What does the `options` block in `pyproject.toml` do? I'm asking mostly because the minimum Python version is 3.8 there and 3.10 in `requires-python`. It might not matter, but maybe best to resolve that early on, just in case.

**Comment by rafmudaf** [comment]
`pyproject.toml` generally looks good to me and the pip installation worked well.

Note that the latest Python version is 3.13 but WISDEM does not yet have a build for that on PyPI since the latest WISDEM release was one day before Python 3.13 was released. Specifying `Python==3.12` when creating my environment got around this issue, and this will be resolved in time.

My only other comment on `pyproject.toml` is to consider cleaning up some of the classifiers and adding a license and url lines.

**Comment by cfrontin** [comment]
The duplicate `requirements.txt` and `pyproject.toml` as well as the python specification and probably also the `options` block are all due to my ignorance on build systems and what I have been able to scrape together. The duplication was because I don't really understand how conda and pip intersect, `options` block is the only way I could figure out how to get the source code to show up on pip install. Feel free to change everything on your end and push and I can rebuild my env (I presume you've got the best way to build for all this holstered for a quick draw).

**Comment by rafmudaf** [comment]
I've removed `requirements.txt` in favor of the dependency list in `pyproject.toml`. We also agreed to support only pip for installing locally from the source code. For distributing windArd, we will configure PyPI and Conda-Forge builds to run upon each GitHub Release.

Additionally, an "installation" block was added to the README, and the `pyproject.toml` configuration was tidied up.
